args: ['python3', 'tulip.py', './tests/type_check_errors/unexpected_data_on_stack.tlp']
-------- stdout ----------
--------------------------
-------- stderr ----------
./tests/type_check_errors/unexpected_data_on_stack.tlp:1:1 [ERROR]: Unhandled data on the datastack.
    [Note]: Expected an empty stack found: [int]
--------------------------
exit code: 1
