args: ['python3', 'tulip.py', './tests/compiler_errors/name_redefinitions/fn_redef_fn.tlp']
-------- stdout ----------
--------------------------
-------- stderr ----------
./tests/compiler_errors/name_redefinitions/fn_redef_fn.tlp:2:4 [ERROR]: Redefinition of `foo`. Previously defined here: ./tests/compiler_errors/name_redefinitions/fn_redef_fn.tlp:1:1
--------------------------
exit code: 1
